### PR TITLE
more factual test of force_interval, dev setup improvement and pep8

### PR DESCRIPTION
**Pull request by anthonyalmarza**

### CODE REVIEW

**Comment by jMyles** [comment]
Hey man.  Welcome home!  I'm not sure why tox isn't running.

**Comment by anthonyalmarza** [comment]
yeah that's weird. I ran the tests locally using `python runtests.py` and everything passed.

**Comment by anthonyalmarza** [comment]
@jMyles yo man are we going to merge this?

**Comment by jMyles** [comment]
Ummm, yeah I think so.  Are you feeling good about it?

**Comment by anthonyalmarza** [comment]
Yeah, it put to bet a pretty large concern of mine.

But I agree it may be a good idea to build out the "last_run" logic.

**Comment by anthonyalmarza** [comment]
After this I want to tag the version and release it to pypi

**Comment by anthonyalmarza** [comment]
i.e. merge it into master

**Comment by jMyles** [comment]
Subsumed by #68

**Pull request closed without merging**
